// AUTO-GENERATED by @rudderjs/orm — do not edit.
// Source: the migrated database schema (run `rudder schema:types` or `migrate`).
import '@rudderjs/orm'

declare module '@rudderjs/orm' {
  interface SchemaRegistry {
    article: {
      id: string
      title: string
      slug: string | null
      excerpt: string | null
      coverImage: string | null
      tags: string
      status: string
      draftStatus: string
      featured: boolean
      publishedAt: string | null
      accentColor: string | null
      metaTitle: string | null
      metaDescription: string | null
      content: string | null
      body: string | null
      metadata: string | null
      deletedAt: string | null
      createdAt: string | null
      updatedAt: string | null
    }
    article_tag: {
      articleId: string
      tagId: string
    }
    comment: {
      id: string
      body: string
      commentableId: string
      commentableType: string
      createdAt: string | null
      updatedAt: string | null
    }
    notification: {
      id: string
      notifiable_id: string
      notifiable_type: string
      type: string
      data: string
      read_at: string | null
      created_at: string
      updated_at: string
    }
    panelGlobal: {
      slug: string
      data: string
      updatedAt: string | null
    }
    post: {
      id: string
      title: string
      body: string | null
      status: string
      authorId: string
      publishedAt: string | null
      deletedAt: string | null
      sort: number
      createdAt: string | null
      updatedAt: string | null
    }
    reply: {
      id: string
      commentId: string
      body: string
      createdAt: string | null
      updatedAt: string | null
    }
    tag: {
      id: string
      name: string
      slug: string
      color: string | null
      createdAt: string | null
      updatedAt: string | null
    }
    taggable: {
      tagId: string
      taggableId: string
      taggableType: string
    }
    user: {
      id: string
      name: string
      email: string
      password: string | null
      emailVerified: number
      image: string | null
      role: string
      rememberToken: string | null
      createdAt: string | null
      updatedAt: string | null
    }
    video: {
      id: string
      title: string
      url: string
      createdAt: string | null
      updatedAt: string | null
    }
  }
}
