// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { SchemaRenderer } from '@pilotiq/pilotiq/react'

export default function PilotiqDashboard() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown>; data?: Record<string, unknown> }
  const { panel, basePath, schemaData, _widgetData } = (ctx.data ?? ctx.viewProps) as any ?? {}
  const hasSchema = schemaData && schemaData.length > 0

  if (hasSchema) return <SchemaRenderer elements={schemaData} widgetData={_widgetData} />

  return (
    <>
      <h1 className="text-2xl font-bold mb-6">
        {panel?.branding?.title ?? panel?.name} Dashboard
      </h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {panel?.resources?.map((r: any) => (
          <a key={r.slug} href={basePath + '/' + r.slug}
             className="block p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 hover:border-indigo-300 dark:hover:border-indigo-600 transition">
            <h3 className="font-semibold text-gray-900 dark:text-gray-100">{r.label}</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Manage {r.label.toLowerCase()}</p>
          </a>
        ))}
      </div>
    </>
  )
}
