// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  if (!import.meta.env.SSR) return false
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 1) return false
  if (!PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0] } }
}
