// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'
import { isPanelBase } from '../_clusterOffset.js'

export const route: RouteSync = (pageContext) => {
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 1) return false
  if (!isPanelBase(parts[0])) return false
  if (import.meta.env.SSR && !PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0]! } }
}
