// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { PageContextServer } from 'vike/types'
import { dispatchPageData } from '@pilotiq/pilotiq'

export const data = async (pageContext: PageContextServer): Promise<unknown> => {
  const viewProps = (pageContext as unknown as { viewProps?: unknown }).viewProps
  if (viewProps !== undefined) return viewProps
  return dispatchPageData(pageContext as Parameters<typeof dispatchPageData>[0])
}
