// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AdminShell } from '@pilotiq/pilotiq/react'

export default function ResourceForm() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { panel, basePath, resource, fields, mode } = ctx.viewProps as any ?? {}
  const title = mode === 'create' ? 'Create ' + resource?.label : 'Edit ' + resource?.label
  return (
    <AdminShell panel={panel} basePath={basePath}>
      <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-6">{title}</h1>
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6">
        <form className="space-y-6">
          {fields?.map((field: any) => (
            <div key={field.name}>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                {field.label}{field.required && <span className="text-red-500 ml-1">*</span>}
              </label>
              {field.fieldType === 'textarea' ? (
                <textarea name={field.name} placeholder={field.placeholder} rows={4}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-indigo-500 outline-none" />
              ) : (
                <input name={field.name}
                  type={field.fieldType === 'email' ? 'email' : field.fieldType === 'number' ? 'number' : field.fieldType === 'date' ? 'date' : 'text'}
                  placeholder={field.placeholder} readOnly={field.readonly} required={field.required}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-indigo-500 outline-none" />
              )}
            </div>
          ))}
          <div className="flex gap-3 pt-4 border-t border-gray-200 dark:border-gray-800">
            <button type="submit" className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition">
              {mode === 'create' ? 'Create' : 'Save'}
            </button>
            <a href={basePath + '/' + resource?.slug}
               className="px-4 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 transition">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </AdminShell>
  )
}
