// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'
import { clusterOffset } from '../_clusterOffset.js'

export const route: RouteSync = (pageContext) => {
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  const off = clusterOffset(parts)
  if (parts.length !== 6 + off) return false
  if (parts[5 + off] === 'edit') return false
  if (import.meta.env.SSR && !PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: {
    basePath:      parts[0]!,
    slug:          parts[1 + off]!,
    id:            parts[2 + off]!,
    relationship:  parts[3 + off]!,
    childId1:      parts[4 + off]!,
    relationship2: parts[5 + off]!,
  } }
}
