// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AppShell } from '@pilotiq/pilotiq/react'
import type { ReactNode } from 'react'

export default function PilotiqLayout({ children }: { children: ReactNode }) {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { panel, basePath, layout } = ctx.viewProps as any ?? {}
  if (!panel) return <>{children}</>
  return (
    <AppShell panel={panel} basePath={basePath} layout={layout}>
      {children}
    </AppShell>
  )
}
