// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AppShell, ThemeProvider, generateThemeCSS, NavigateProvider } from '@pilotiq/pilotiq/react'
import { navigate as vikeNavigate } from 'vike/client/router'
import { componentRegistry, rightPanelRegistry, settingsPaneRegistry, layoutProviderRegistry, componentSlotRegistry } from './_components.js'
import type { ReactNode } from 'react'

// Wrap vike's async navigate so the NavigateProvider's fire-and-forget
// signature is satisfied. `scrollToTop: false` keeps the user's scroll
// position across SPA-only updates (filter changes, sort, pagination).
const navigate = (url: string): void => {
  void vikeNavigate(url, { scrollToTop: false } as any)
}

export default function PilotiqLayout({ children }: { children: ReactNode }) {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown>; data?: Record<string, unknown>; urlPathname?: string }
  const data = (ctx.data ?? ctx.viewProps) as any ?? {}
  const { panel, basePath, layout, notifications } = data
  // Hoist the page breadcrumb into the layout header (sidebar layout).
  // Prefer a breadcrumbs element in schemaData; fall back to a dedicated
  // `data.breadcrumb` (used by the settings shell, whose render panes
  // carry no schemaData).
  const breadcrumb = (Array.isArray(data.schemaData) ? data.schemaData.find((e: any) => e && e.type === 'breadcrumbs') : undefined) ?? data.breadcrumb
  const currentPath = ctx.urlPathname
  if (!panel) return <NavigateProvider navigate={navigate}>{children}</NavigateProvider>

  // SSR: inject theme CSS inline to prevent FOUC
  const themeCss = panel.theme ? generateThemeCSS(panel.theme) : null

  return (
    <NavigateProvider navigate={navigate}>
      <ThemeProvider theme={panel.theme}>
        {themeCss && <style dangerouslySetInnerHTML={{ __html: themeCss }} />}
        <AppShell panel={panel} basePath={basePath} layout={layout} notifications={notifications} breadcrumb={breadcrumb} currentPath={currentPath ?? ''} componentRegistry={componentRegistry as any} rightPanelRegistry={rightPanelRegistry as any} settingsPaneRegistry={settingsPaneRegistry as any} layoutProviderRegistry={layoutProviderRegistry as any} componentSlotRegistry={componentSlotRegistry as any}>
          {children}
        </AppShell>
      </ThemeProvider>
    </NavigateProvider>
  )
}
