// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { PageContext } from 'vike/types'

export default function title(pageContext: PageContext): string {
  const ctx = pageContext as unknown as { data?: Record<string, unknown>; viewProps?: Record<string, unknown> }
  const data = (ctx.data ?? ctx.viewProps ?? {}) as any
  const panel = data.panel ?? {}
  const brand: string = panel.branding?.title ?? panel.name ?? 'Pilotiq'

  // Per-role title stamped server-side by the page-data builders.
  let page: string | undefined = typeof data.title === 'string' && data.title ? data.title : undefined

  // Fallbacks for any page that didn't stamp one: the breadcrumb chain
  // encodes the human label per role (its last rung is the page), then
  // a level-1 page heading (e.g. dashboard).
  if (!page) {
    const schema: any[] = Array.isArray(data.schemaData) ? data.schemaData : []
    const crumbs = schema.find((e: any) => e && e.type === 'breadcrumbs')
    if (crumbs && Array.isArray(crumbs.items) && crumbs.items.length > 0) {
      page = crumbs.items[crumbs.items.length - 1]?.label
    }
    if (!page) {
      const heading = schema.find((e: any) => e && e.type === 'heading' && e.level === 1)
      page = heading?.content
    }
  }

  return page && page !== brand ? `${page} · ${brand}` : brand
}
