// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { clusterSlugsByBasePath, panelBasePaths } from './_components.js'

export function clusterOffset(parts: string[]): number {
  if (parts.length < 2) return 0
  const slugs = clusterSlugsByBasePath['/' + parts[0]]
  return slugs && slugs.includes(parts[1]!) ? 1 : 0
}

// First URL segment of every registered panel's base path. Route stubs gate
// on this in BOTH passes — the registry-based gate is SSR-only (the registry
// is empty in the browser), and an ungated client match makes Vike route
// functions (which outrank route strings) steal app URLs of the same segment
// count: SPA nav to e.g. /articles/:slug rendered pilotiq's empty SlugPage.
const PANEL_BASE_SEGMENTS = new Set(
  panelBasePaths.map((p) => p.split('/').filter(Boolean)[0] ?? '').filter(Boolean),
)
export function isPanelBase(firstSegment: string | undefined): boolean {
  return firstSegment !== undefined && PANEL_BASE_SEGMENTS.has(firstSegment)
}
