// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
// Imports each registered Pilotiq instance and walks its config to
// expose every Resource/Global/Page class as `componentRegistry[ClassName]`.
// The renderer uses this to resolve component-typed icons.

import { pilotiqAdmin, pilotiqSimple } from '../../app/Pilotiq/AdminPanel'

const _all: Record<string, unknown> = {}
const _clusters: Record<string, string[]> = {}
const _rightPanels: Record<string, unknown> = {}
const _layoutProviders: unknown[] = []
function _add(c: any) { if (typeof c === 'function' && c.name) _all[c.name] = c }
function _walk(p: any) {
  const cfg = p?.getConfig?.()
  cfg?.resources?.forEach(_add)
  cfg?.globals?.forEach(_add)
  cfg?.pages?.forEach(_add)
  if (Array.isArray(cfg?.rightPanels)) {
    for (const _c of cfg.rightPanels) {
      if (_c && typeof _c.id === 'string' && _c.render) _rightPanels[_c.id] = _c.render
    }
  }
  if (Array.isArray(cfg?.layoutProviders)) {
    for (const _C of cfg.layoutProviders) {
      if (typeof _C === 'function') _layoutProviders.push(_C)
    }
  }
  if (cfg?.path && Array.isArray(cfg?.clusters)) {
    const slugs = cfg.clusters.map((C: any) => (typeof C?.getSlug === 'function' ? C.getSlug() : '')).filter(Boolean)
    if (slugs.length > 0) _clusters[cfg.path] = slugs
  }
}
for (const _p of [pilotiqAdmin, pilotiqSimple]) _walk(_p)

export const componentRegistry: Record<string, unknown> = _all
export const clusterSlugsByBasePath: Record<string, string[]> = _clusters
export const rightPanelRegistry: Record<string, unknown> = _rightPanels
export const layoutProviderRegistry: unknown[] = _layoutProviders
