// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'

export default function ResourceForm() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { basePath, resource, fields, mode } = ctx.viewProps as any ?? {}
  const title = mode === 'create' ? 'Create ' + resource?.label : 'Edit ' + resource?.label
  return (
    <>
      <h1 className="text-2xl font-bold mb-6">{title}</h1>
      <div className="rounded-xl border bg-card p-6">
        <form className="space-y-6">
          {fields?.map((field: any) => (
            <div key={field.name}>
              <label className="block text-sm font-medium mb-1">
                {field.label}{field.required && <span className="text-destructive ml-1">*</span>}
              </label>
              {field.fieldType === 'textarea' ? (
                <textarea name={field.name} placeholder={field.placeholder} rows={4}
                  className="w-full px-3 py-2 border rounded-lg text-sm bg-background focus:ring-2 focus:ring-ring outline-none" />
              ) : (
                <input name={field.name}
                  type={field.fieldType === 'email' ? 'email' : field.fieldType === 'number' ? 'number' : field.fieldType === 'date' ? 'date' : 'text'}
                  placeholder={field.placeholder} readOnly={field.readonly} required={field.required}
                  className="w-full px-3 py-2 border rounded-lg text-sm bg-background focus:ring-2 focus:ring-ring outline-none" />
              )}
            </div>
          ))}
          <div className="flex gap-3 pt-4 border-t">
            <button type="submit" className="px-4 py-2 bg-primary text-primary-foreground text-sm font-medium rounded-lg hover:bg-primary/90 transition">
              {mode === 'create' ? 'Create' : 'Save'}
            </button>
            <a href={basePath + '/' + resource?.slug}
               className="px-4 py-2 text-sm text-muted-foreground hover:text-foreground transition">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </>
  )
}
