// AUTO-GENERATED by @rudderjs/orm — do not edit.
// Source: the migrated database schema (run `rudder schema:types` or `migrate`).
import '@rudderjs/orm'

declare module '@rudderjs/orm' {
  interface SchemaRegistry {
    category: {
      id: string
      name: string
      slug: string
      description: string | null
      createdAt: string | null
      updatedAt: string | null
    }
    category_post: {
      categoryId: string
      postId: string
    }
    comment: {
      id: string
      postId: string
      authorName: string | null
      body: string
      createdAt: string | null
      updatedAt: string | null
    }
    media: {
      id: string
      name: string
      type: string
      mime: string | null
      size: number | null
      disk: string
      directory: string
      filename: string | null
      width: number | null
      height: number | null
      focalX: number | null
      focalY: number | null
      conversions: unknown | null
      alt: string | null
      meta: unknown | null
      parentId: string | null
      scope: string
      userId: string | null
      createdAt: string | null
      updatedAt: string | null
    }
    notification: {
      id: string
      notifiable_id: string
      notifiable_type: string
      type: string
      data: string
      read_at: string | null
      created_at: string
      updated_at: string
    }
    page: {
      id: string
      title: string
      slug: string
      content: unknown | null
      published: boolean
      createdAt: string | null
      updatedAt: string | null
    }
    panelGlobal: {
      slug: string
      data: string
      updatedAt: string | null
    }
    post: {
      id: string
      title: string
      slug: string
      status: string
      publishedAt: Date | null
      image: unknown | null
      content: unknown | null
      metaTitle: string | null
      metaDescription: string | null
      deletedAt: string | null
      createdAt: string | null
      updatedAt: string | null
      metaImage: string | null
      excerpt: string | null
      gallery: unknown | null
      coverMedia: unknown | null
    }
    post_author: {
      postId: string
      userId: string
    }
    post_related: {
      postId: string
      relatedId: string
    }
    user: {
      id: string
      name: string
      email: string
      password: string | null
      emailVerified: boolean
      image: string | null
      role: string
      rememberToken: string | null
      createdAt: string | null
      updatedAt: string | null
    }
  }
}
