// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AppShell, ThemeProvider, generateThemeCSS, NavigateProvider } from '@pilotiq/pilotiq/react'
import { navigate as vikeNavigate } from 'vike/client/router'
import type { ReactNode } from 'react'

// Wrap vike's async navigate so the NavigateProvider's fire-and-forget
// signature is satisfied. `scrollToTop: false` keeps the user's scroll
// position across SPA-only updates (filter changes, sort, pagination).
const navigate = (url: string): void => {
  void vikeNavigate(url, { scrollToTop: false } as any)
}

export default function PilotiqLayout({ children }: { children: ReactNode }) {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown>; data?: Record<string, unknown> }
  const { panel, basePath, layout, notifications } = (ctx.data ?? ctx.viewProps) as any ?? {}
  if (!panel) return <NavigateProvider navigate={navigate}>{children}</NavigateProvider>

  // SSR: inject theme CSS inline to prevent FOUC
  const themeCss = panel.theme ? generateThemeCSS(panel.theme) : null

  return (
    <NavigateProvider navigate={navigate}>
      <ThemeProvider theme={panel.theme}>
        {themeCss && <style dangerouslySetInnerHTML={{ __html: themeCss }} />}
        <AppShell panel={panel} basePath={basePath} layout={layout} notifications={notifications}>
          {children}
        </AppShell>
      </ThemeProvider>
    </NavigateProvider>
  )
}
