// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AppShell, ThemeProvider, generateThemeCSS } from '@pilotiq/pilotiq/react'
import type { ReactNode } from 'react'

export default function PilotiqLayout({ children }: { children: ReactNode }) {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown>; data?: Record<string, unknown> }
  const { panel, basePath, layout } = (ctx.data ?? ctx.viewProps) as any ?? {}
  if (!panel) return <>{children}</>

  // SSR: inject theme CSS inline to prevent FOUC
  const themeCss = panel.theme ? generateThemeCSS(panel.theme) : null

  return (
    <ThemeProvider theme={panel.theme}>
      {themeCss && <style dangerouslySetInnerHTML={{ __html: themeCss }} />}
      <AppShell panel={panel} basePath={basePath} layout={layout}>
        {children}
      </AppShell>
    </ThemeProvider>
  )
}
