// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
// Imports each registered Pilotiq instance and walks its config to
// expose every Resource/Global/Page class as `componentRegistry[ClassName]`.
// The renderer uses this to resolve component-typed icons.

import { pilotiqAdmin, pilotiqSimple } from '../../app/Pilotiq/AdminPanel'

const _all: Record<string, unknown> = {}
function _add(c: any) { if (typeof c === 'function' && c.name) _all[c.name] = c }
function _walk(p: any) {
  const cfg = p?.getConfig?.()
  cfg?.resources?.forEach(_add)
  cfg?.globals?.forEach(_add)
  cfg?.pages?.forEach(_add)
}
for (const _p of [pilotiqAdmin, pilotiqSimple]) _walk(_p)

export const componentRegistry: Record<string, unknown> = _all
