/**
 * Vite plugin that generates Vike page stubs for @pilotiq/pilotiq.
 *
 * Stubs are written at plugin construction time (before Vike scans pages/).
 * They use route functions that check PilotiqRegistry at request time, so
 * they work for any number of registered panels without regeneration.
 */
import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

function writeIfChanged(filePath: string, contents: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, 'utf8')
    if (existing === contents) return
  }
  fs.writeFileSync(filePath, contents)
}

function generatePages(pagesRoot: string): void {
  const outDir = path.join(pagesRoot, '(pilotiq)')

  // Shared config
  writeIfChanged(path.join(outDir, '+config.ts'), `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { Config } from 'vike/types'

export default {
  passToClient: ['viewProps'],
} satisfies Config
`)

  // Shared data stub
  const dataStub = `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { PageContextServer } from 'vike/types'
export const data = (_pageContext: PageContextServer): null => null
`

  // ── Dashboard ────────────────────────────────────────────
  writeIfChanged(path.join(outDir, 'dashboard', '+route.ts'), `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  if (!import.meta.env.SSR) return false
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 1) return false
  if (!PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0] } }
}
`)
  writeIfChanged(path.join(outDir, 'dashboard', '+data.ts'), dataStub)
  writeIfChanged(path.join(outDir, 'dashboard', '+Page.tsx'), `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AdminShell } from '@pilotiq/pilotiq/react'

export default function PilotiqDashboard() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { panel, basePath } = ctx.viewProps as any ?? {}
  return (
    <AdminShell panel={panel} basePath={basePath}>
      <h1 className="text-2xl font-bold mb-6">
        {panel?.branding?.title ?? panel?.name} Dashboard
      </h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {panel?.resources?.map((r: any) => (
          <a key={r.slug} href={basePath + '/' + r.slug}
             className="block p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 hover:border-indigo-300 dark:hover:border-indigo-600 transition">
            <h3 className="font-semibold text-gray-900 dark:text-gray-100">{r.label}</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Manage {r.label.toLowerCase()}</p>
          </a>
        ))}
      </div>
    </AdminShell>
  )
}
`)

  // ── Resource Index ────────────────────────────────────────
  writeIfChanged(path.join(outDir, 'resource-index', '+route.ts'), `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  if (!import.meta.env.SSR) return false
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 2) return false
  if (!PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0], slug: parts[1] } }
}
`)
  writeIfChanged(path.join(outDir, 'resource-index', '+data.ts'), dataStub)
  writeIfChanged(path.join(outDir, 'resource-index', '+Page.tsx'), `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AdminShell } from '@pilotiq/pilotiq/react'

export default function ResourceIndex() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { panel, basePath, resource, columns } = ctx.viewProps as any ?? {}
  return (
    <AdminShell panel={panel} basePath={basePath}>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">{resource?.label}</h1>
        <a href={basePath + '/' + resource?.slug + '/create'}
           className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition">
          Create {resource?.labelSingular}
        </a>
      </div>
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-800">
            <tr>
              {columns?.map((col: any) => (
                <th key={col.name} className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                  {col.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colSpan={columns?.length ?? 1} className="px-4 py-12 text-center text-gray-400 dark:text-gray-500">
                No records yet.
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </AdminShell>
  )
}
`)

  // ── Resource Create ───────────────────────────────────────
  writeIfChanged(path.join(outDir, 'resource-create', '+route.ts'), `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  if (!import.meta.env.SSR) return false
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 3 || parts[2] !== 'create') return false
  if (!PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0], slug: parts[1] } }
}
`)
  writeIfChanged(path.join(outDir, 'resource-create', '+data.ts'), dataStub)

  // ── Resource Edit ─────────────────────────────────────────
  writeIfChanged(path.join(outDir, 'resource-edit', '+route.ts'), `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  if (!import.meta.env.SSR) return false
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 4 || parts[3] !== 'edit') return false
  if (!PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0], slug: parts[1], id: parts[2] } }
}
`)
  writeIfChanged(path.join(outDir, 'resource-edit', '+data.ts'), dataStub)

  // Create and Edit share the same form page component
  const formPage = `// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { AdminShell } from '@pilotiq/pilotiq/react'

export default function ResourceForm() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { panel, basePath, resource, fields, mode } = ctx.viewProps as any ?? {}
  const title = mode === 'create' ? 'Create ' + resource?.label : 'Edit ' + resource?.label
  return (
    <AdminShell panel={panel} basePath={basePath}>
      <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-6">{title}</h1>
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6">
        <form className="space-y-6">
          {fields?.map((field: any) => (
            <div key={field.name}>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                {field.label}{field.required && <span className="text-red-500 ml-1">*</span>}
              </label>
              {field.fieldType === 'textarea' ? (
                <textarea name={field.name} placeholder={field.placeholder} rows={4}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-indigo-500 outline-none" />
              ) : (
                <input name={field.name}
                  type={field.fieldType === 'email' ? 'email' : field.fieldType === 'number' ? 'number' : field.fieldType === 'date' ? 'date' : 'text'}
                  placeholder={field.placeholder} readOnly={field.readonly} required={field.required}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-indigo-500 outline-none" />
              )}
            </div>
          ))}
          <div className="flex gap-3 pt-4 border-t border-gray-200 dark:border-gray-800">
            <button type="submit" className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition">
              {mode === 'create' ? 'Create' : 'Save'}
            </button>
            <a href={basePath + '/' + resource?.slug}
               className="px-4 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 transition">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </AdminShell>
  )
}
`
  writeIfChanged(path.join(outDir, 'resource-create', '+Page.tsx'), formPage)
  writeIfChanged(path.join(outDir, 'resource-edit', '+Page.tsx'), formPage)
}

export function pilotiqPages(): Plugin {
  const cwd = process.cwd()
  const pagesRoot = path.join(cwd, 'pages')

  // Generate at construction time — before Vike scans pages/
  generatePages(pagesRoot)

  return {
    name: 'pilotiq:pages',
    enforce: 'pre',
    buildStart() {
      generatePages(pagesRoot)
    },
  }
}
