// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { SchemaRenderer } from '@pilotiq/pilotiq/react'

export default function SlugPage() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown>; data?: Record<string, unknown> }
  const vp = (ctx.data ?? ctx.viewProps) as any ?? {}
  return <SchemaRenderer elements={vp.schemaData ?? []} />
}
