// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { SchemaRenderer } from '@pilotiq/pilotiq/react'

export default function CustomPage() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { schemaData } = ctx.viewProps as any ?? {}
  return <SchemaRenderer elements={schemaData ?? []} />
}
