// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 2) return false
  // Don't match built-in slugs (theme editor, etc.) or resource slugs
  if (parts[1] === 'theme') return false
  if (import.meta.env.SSR) {
    const panel = PilotiqRegistry.findByPath('/' + parts[0])
    if (!panel) return false
    // Check it's a registered page, not a resource
    const cfg = panel.getConfig()
    const isResource = cfg.resources.some((R: any) => (R.constructor as any).getSlug() === parts[1])
    if (isResource) return false
  }
  return { routeParams: { basePath: parts[0], pageSlug: parts[1] } }
}
