// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { navigate } from 'vike/client/router'
import { ThemeSettingsPage } from '@pilotiq/pilotiq/react'

const handleNavigate = (url: string) => navigate(url, { overwriteLastHistoryEntry: true, scrollToTop: false } as any)

export default function ThemeEditorPage() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const { basePath, themeConfig } = ctx.viewProps as any ?? {}
  return <ThemeSettingsPage panelPath={basePath} initialConfig={themeConfig} onNavigate={handleNavigate} />
}
