// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 3) return false
  // Don't shadow create page or theme editor.
  if (parts[2] === 'create') return false
  if (parts[1] === 'theme')  return false
  if (import.meta.env.SSR && !PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0], slug: parts[1], id: parts[2] } }
}
