// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import { usePageContext } from 'vike-react/usePageContext'
import { SettingsShell } from '@pilotiq/pilotiq/react'

export default function SettingsPage() {
  const ctx = usePageContext() as unknown as {
    viewProps?: Record<string, unknown>
    data?: Record<string, unknown>
    routeParams?: Record<string, string>
    urlPathname?: string
  }
  const data = (ctx.data ?? ctx.viewProps) as any ?? {}
  const panes = data?.panel?.settings?.panes ?? []
  const basePath = data?.basePath ?? ('/' + (ctx.routeParams?.basePath ?? ''))
  const paneId = ctx.routeParams?.paneId || data?.activePaneId
  const schemaData = data?.schemaData
  return <SettingsShell basePath={basePath} panes={panes}
    {...(paneId ? { activePaneId: paneId } : {})}
    {...(schemaData ? { schemaData } : {})}
    {...(ctx.urlPathname ? { currentPath: ctx.urlPathname } : {})} />
}
