// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'
import { isPanelBase } from '../_clusterOffset.js'

export const route: RouteSync = (pageContext) => {
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 2 && parts.length !== 3) return false
  if (parts[1] !== 'settings') return false
  if (!isPanelBase(parts[0])) return false
  if (import.meta.env.SSR) {
    const panel = PilotiqRegistry.findByPath('/' + parts[0])
    if (!panel) return false
    const cfg = panel.getConfig()
    // Only match when the panel actually exposes settings.
    if ((cfg.settingsPanes?.length ?? 0) === 0 && !cfg.profilePage) return false
  }
  return { routeParams: { basePath: parts[0]!, paneId: parts[2] ?? '' } }
}
