// AUTO-GENERATED by @pilotiq/pilotiq — do not edit.
import type { RouteSync } from 'vike/types'
import { PilotiqRegistry } from '@pilotiq/pilotiq/registry'

export const route: RouteSync = (pageContext) => {
  const parts = pageContext.urlPathname.split('/').filter(Boolean)
  if (parts.length !== 6 || parts[5] !== 'edit') return false
  if (import.meta.env.SSR && !PilotiqRegistry.findByPath('/' + parts[0])) return false
  return { routeParams: { basePath: parts[0], slug: parts[1], id: parts[2], relationship: parts[3], childId: parts[4] } }
}
